# Generated by Django 3.2.8 on 2021-11-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211116_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_product',
            new_name='product',
        ),
    ]
