# Generated by Django 3.2.8 on 2021-11-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_product_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
