# Generated by Django 3.2.8 on 2021-11-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_order_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
