# Generated by Django 3.2.8 on 2021-11-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20211117_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
