# Generated by Django 3.2.8 on 2021-11-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_rename_product_code_product_product_code_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_code_id',
            new_name='product_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
